name: fp_modal
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-268.18.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^2.1.0
  # localization helper
  intl: ^0.17.0
  # localization automation
  intl_utils: ^2.4.0
  flutter_platform_widgets: ^1.11.0
  material_color_utilities: ^0.1.2
  dynamic_color: ^0.1.0
  adaptive_breakpoints: ^0.1.1
  flutter_portal: ^0.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  # code metrics
  dart_code_metrics: ^4.5.0


  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - google_fonts/
# flutter intl for localization settings
flutter_intl:
  enabled: true   
  class_name: S   
  main_locale: en 
  arb_dir: lib/src/localization
  output_dir: lib/src/localization_gen
  use_deferred_loading: false

